name: bryte
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animated_segmented_tab_control: ^1.0.1
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  custom_sliding_segmented_control: ^1.5.2
  dio: ^4.0.4
  dropdown_button2: ^1.7.2
  file_picker: ^3.0.4
  fl_downloader: ^1.0.2
  fluentui_system_icons: ^1.1.174
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_downloader: ^1.8.1
  flutter_html: ^2.2.1
  flutter_svg: ^0.23.0+1
  fluttertoast: ^8.0.9
  get: ^4.6.5
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  injectable: ^1.5.3
  injectable_generator: ^1.5.3
  intl: ^0.17.0
  jiffy: ^5.0.0
  path_provider: ^2.0.11
  pin_code_fields: ^7.3.0
  pretty_dio_logger: ^1.1.1
  readmore: ^2.1.0
  recase: ^4.0.0
  scrollable_positioned_list: ^0.3.5
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_pdfviewer: ^20.2.38-beta
  table_calendar: ^3.0.8
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.1.7
  flutter_flavorizr: ^2.1.3
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5

flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    development:
      app:
        name: "Development Flavor"

      android:
        applicationId: "com.prasmul.bryte.dev"

      ios:
        bundleId: "com.prasmul.bryte.dev"
        buildSettings:
          # Development Team is visible in the apple developer portal 
          DEVELOPMENT_TEAM: YOURDEVTEAMID 
          PROVISIONING_PROFILE_SPECIFIER: "Dev-ProvisioningProfile"

    staging:
      app:
        name: "Staging App"

      android:
        applicationId: "com.prasmul.bryte.stg"
      ios:
        bundleId: "com.prasmul.bryte.stg"
        buildSettings:
          DEVELOPMENT_TEAM: YOURSTAGINGTEAMID
          PROVISIONING_PROFILE_SPECIFIER: "Staging-ProvisioningProfile"

    production:
      app:
        name: "Production App"

      android:
        applicationId: "com.prasmul.bryte"
      ios:
        bundleId: "com.prasmul.bryte"
        buildSettings:
          DEVELOPMENT_TEAM: YOURPRODUCTIONTEAMID
          PROVISIONING_PROFILE_SPECIFIER: "Production-ProvisioningProfile"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/rummage/

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
    - family: SF Pro Bold
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
